### PR TITLE
Remove references to school

### PR DESCRIPTION
**Pull request by colinstrancd2l**
Should be done after [user tile stops referencing school](https://github.com/Brightspace/user-tile/pull/29/files) and [user switcher stops referencing school](https://github.com/Brightspace/user-switcher/pull/24).

### CODE REVIEW

**Comment by ryantmer** [comment]
Definitely not needed to be done here, but interestingly enough this could completely change how we fetch this data (for the better).

Previously, we needed to fetch the root, then the institution, to get the school name, as well as the theme if required. Now, however, the school is no longer required, meaning we can skip the root -> institution -> theme requests if we end up using a course image rather than the theme colour for the user-tile (ultimately reducing our call count from 7 to 3).

But, yeah, not for this PR :P

**Comment by colinstrancd2l** [comment]
Haha, I was a little curious if this was wise, but I had just got rid of every example of school that the search could find, so figured maybe it was good to go.

**Comment by ryantmer** [comment]
Yep, I do believe you are in this case :) It's more of a "just so happens to also be that-" kind of thing.

**Comment by colinstrancd2l** [comment]
Should I close the PR?

**Comment by ryantmer** [comment]
Whoops - I meant "I do believe you are good to go in this case". So this PR has value in itself, as well as opening up an opportunity for even further improvement!

**Comment by jstefaniuk-d2l** [comment]
Yeah, I can make some changes to the request making for my current story

**Comment by ryantmer** [comment]
🙌 

Using `d2lfetch` would also be legit, but in speaking with @CodeBaboon, we're going to want to hold off on that until we're 1.0.0-ified there and know that things are working as intended, before spreading it everywhere.

**Pull request merged**
