### PR TITLE
US87150 - User title fade in

### PR DESCRIPTION
**Pull request by jstefaniuk-d2l**
Based off of https://github.com/Brightspace/user-profile-behavior/pull/12

Pretty much adds a flag saying "stuff is done loading" for use in the user tile

Also: https://github.com/Brightspace/user-tile/pull/30

### CODE REVIEW

**Comment by jstefaniuk-d2l** [comment]
Todo: 
- make it respect the "background" option
- maybe preload the image

**Comment by ryantmer** [comment]
Should this have some sort of timeout? I'm just thinking if one of the (many) calls fails, it'll never fade in - but maybe we could just cut our losses after 3-4 seconds and fade in whatever we do have or something?

**Comment by jstefaniuk-d2l** [comment]
The background calls are all set up to set the `background-color:` to `initial` if they fail to the point of no-return, so those won't be a problem

Thought:
if we don't have the student's name, does revealing the tile make a difference anyways?

**Comment by ryantmer** [comment]
Hm, yeah fair - although having one of either profile picture or name would be more useful than having neither. Can probably a future consideration, though, if it comes up.

**Comment by jstefaniuk-d2l** [comment]
Also, the profile icon comes back in the same request as the name, so unless for some super odd reason the child doesn't have permission to see their own name we'll either get both the pic & name, or just the name

**Comment by ryantmer** [comment]
Oh, true as well. I was thinking more for the course image, since the call hierarchy is

- user - gets us the name/profile image
  - root
    - institution
      - theme - gets us the backgroundColour
- enrollments
  - organizations (if only one enrollment)
    - organization image - gets us the background image

Ostensibly user and enrollments get fired at the same time, but it _could_ mean that we're waiting for another two calls (plus the fetch of the actual image) before the background image is visible. But, it occurs to me now that I've typed this whole comment that I think this is exactly what you illustrated above as "those won't be a problem" because of the `inherit` on problems... so... I guess ignore this comment 😜

**Pull request merged**
